(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-NEW-BUFFER-URL "www.gnu.org")))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 1.0)))
(DEFINE-CONFIGURATION NYXT/WEB-MODE:USER-WEB-MODE
  ((NYXT/WEB-MODE:HINTS-ALPHABET "aqwszxpmlok")))
